---
trigger:
  paths:
    include:
      - .azdo/pipelines/management-groups.yml
      - environments/canary/management-groups.bicepparam
      - environments/prod/management-groups.bicepparam
      - modules/management-groups/**
    exclude:
      - README.md

variables:
  vmImage: ubuntu-latest

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: build
        displayName: Build
        variables:
          - template: ../../environments/canary/vars.yml
        pool:
          vmImage: $(vmImage)
        steps:
          - task: AzureCLI@2
            displayName: Build Template
            inputs:
              azureSubscription: ${{ variables.azureConnection }}
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az bicep build --file modules/management-groups/main.bicep --outfile $(Build.ArtifactStagingDirectory)/main.json
                az bicep build-params --file environments/canary/management-groups.bicepparam --outfile $(Build.ArtifactStagingDirectory)/main.canary.parameters.json
                az bicep build-params --file environments/prod/management-groups.bicepparam --outfile $(Build.ArtifactStagingDirectory)/main.prod.parameters.json

          - task: PublishPipelineArtifact@1
            displayName: Publish Artifacts
            inputs:
              targetPath: $(Build.ArtifactStagingDirectory)
              artifact: drop
              publishLocation: pipeline

  - stage: validate
    displayName: Validate
    dependsOn: build
    jobs:
      - deployment: canary
        displayName: Canary
        condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/main'))
        variables:
          - template: ../../environments/canary/vars.yml
        pool:
          vmImage: $(vmImage)
        environment: Canary
        strategy:
          runOnce:
            deploy:
              steps:
                - template: templates/tenant-deployment.yml
                  parameters:
                    deploymentName: management-groups
                    environment: canary
                    command: validate
                    azureConnection: ${{ variables.azureConnection }}
                    location: ${{ variables.location }}

                - template: templates/tenant-deployment.yml
                  parameters:
                    deploymentName: management-groups
                    environment: canary
                    command: what-if
                    azureConnection: ${{ variables.azureConnection }}
                    location: ${{ variables.location }}

      - deployment: prod
        displayName: Production
        variables:
          - template: ../../environments/prod/vars.yml
        pool:
          vmImage: $(vmImage)
        environment: Production
        strategy:
          runOnce:
            deploy:
              steps:
                - template: templates/tenant-deployment.yml
                  parameters:
                    deploymentName: management-groups
                    environment: prod
                    command: validate
                    azureConnection: ${{ variables.azureConnection }}
                    location: ${{ variables.location }}

                - template: templates/tenant-deployment.yml
                  parameters:
                    deploymentName: management-groups
                    environment: prod
                    command: what-if
                    azureConnection: ${{ variables.azureConnection }}
                    location: ${{ variables.location }}

  - stage: deploy
    displayName: Deploy
    dependsOn: validate
    jobs:
      - deployment: canary
        displayName: Canary
        condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/main'))
        variables:
          - template: ../../environments/canary/vars.yml
        pool:
          vmImage: $(vmImage)
        environment: Canary
        strategy:
          runOnce:
            deploy:
              steps:
                - template: templates/tenant-deployment.yml
                  parameters:
                    deploymentName: management-groups
                    environment: canary
                    command: create
                    azureConnection: ${{ variables.azureConnection }}
                    location: ${{ variables.location }}

      - deployment: prod
        displayName: Production
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
        variables:
          - template: ../../environments/prod/vars.yml
        pool:
          vmImage: $(vmImage)
        environment: Production
        strategy:
          runOnce:
            deploy:
              steps:
                - template: templates/tenant-deployment.yml
                  parameters:
                    deploymentName: management-groups
                    environment: prod
                    command: create
                    azureConnection: ${{ variables.azureConnection }}
                    location: ${{ variables.location }}
