---
parameters:
  - name: deploymentName
  - name: environment
  - name: command
  - name: azureConnection
  - name: location
  - name: managementGroupId
  - name: templateFile
  - name: parameters

steps:
  - task: AzureCLI@2
    displayName: Management Group Deployment (${{ parameters.command }}) (${{ parameters.environment }})
    inputs:
      azureSubscription: ${{ parameters.azureConnection }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az deployment mg ${{ parameters.command }} \
        --management-group-id ${{ parameters.managementGroupId }} \
        --name "${{ parameters.deploymentName }}-$(date -u +"%Y%m%d%H%M%S")" \
        --location ${{ parameters.location }} \
        --template-file ${{ parameters.templateFile }} \
        --parameters ${{ parameters.parameters }}
      failOnStandardError: true
