---
parameters:
  - name: deploymentName
  - name: environment
  - name: command
  - name: azureConnection
  - name: location

steps:
  - task: AzureCLI@2
    displayName: Tenant Deployment (${{ parameters.command }}) (${{ parameters.environment }})
    inputs:
      azureSubscription: ${{ parameters.azureConnection }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az deployment tenant ${{ parameters.command }} \
        --name "${{ parameters.deploymentName }}-$(date -u +"%Y%m%d%H%M%S")" \
        --location ${{ parameters.location }} \
        --template-file $(Pipeline.Workspace)/drop/main.json \
        --parameters $(Pipeline.Workspace)/drop/main.${{ parameters.environment }}.parameters.json
