---
parameters:
  - name: displayName
  - name: deploymentName
  - name: environment
  - name: command
  - name: azureConnection
  - name: location
  - name: templateFile
  - name: parameters

steps:
  - task: AzureCLI@2
    displayName: ${{ parameters.displayName }}
    inputs:
      azureSubscription: ${{ parameters.azureConnection }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az deployment tenant ${{ parameters.command }} \
        --name "${{ parameters.deploymentName }}-$(date -u +"%Y%m%d%H%M%S")" \
        --location ${{ parameters.location }} \
        --template-file ${{ parameters.templateFile }} \
        --parameters ${{ parameters.parameters }}
      failOnStandardError: true
